CREATE TABLE malha (id_malha INT NOT NULL IDENTITY, nm_malha VARCHAR(80) NOT NULL, PRIMARY KEY (id_malha));
CREATE TABLE trecho (id_trecho INT NOT NULL IDENTITY, id_malha INT NOT NULL, nm_origem VARCHAR(45) NOT NULL, nm_destino VARCHAR(45) NOT NULL, vl_distancia DECIMAL(5,2) NOT NULL, PRIMARY KEY (id_trecho));
CREATE SEQUENCE malha_sequence START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE trecho_sequence START WITH 1 INCREMENT BY 1;
