
package webservice.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Entrega", targetNamespace = "http://impl.webservice/", wsdlLocation = "http://localhost:8080/smartlogic/ws/entrega?wsdl")
public class Entrega
    extends Service
{

    private final static URL ENTREGA_WSDL_LOCATION;
    private final static WebServiceException ENTREGA_EXCEPTION;
    private final static QName ENTREGA_QNAME = new QName("http://impl.webservice/", "Entrega");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/smartlogic/ws/entrega?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ENTREGA_WSDL_LOCATION = url;
        ENTREGA_EXCEPTION = e;
    }

    public Entrega() {
        super(__getWsdlLocation(), ENTREGA_QNAME);
    }

    public Entrega(WebServiceFeature... features) {
        super(__getWsdlLocation(), ENTREGA_QNAME, features);
    }

    public Entrega(URL wsdlLocation) {
        super(wsdlLocation, ENTREGA_QNAME);
    }

    public Entrega(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ENTREGA_QNAME, features);
    }

    public Entrega(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Entrega(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EntregaEndpointWS
     */
    @WebEndpoint(name = "EntregaEndpointWSPort")
    public EntregaEndpointWS getEntregaEndpointWSPort() {
        return super.getPort(new QName("http://impl.webservice/", "EntregaEndpointWSPort"), EntregaEndpointWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EntregaEndpointWS
     */
    @WebEndpoint(name = "EntregaEndpointWSPort")
    public EntregaEndpointWS getEntregaEndpointWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.webservice/", "EntregaEndpointWSPort"), EntregaEndpointWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ENTREGA_EXCEPTION!= null) {
            throw ENTREGA_EXCEPTION;
        }
        return ENTREGA_WSDL_LOCATION;
    }

}
