
package webservice.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EntregaEndpointWS", targetNamespace = "http://impl.webservice/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EntregaEndpointWS {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.Double
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "calcularCusto", targetNamespace = "http://impl.webservice/", className = "webservice.impl.CalcularCusto")
    @ResponseWrapper(localName = "calcularCustoResponse", targetNamespace = "http://impl.webservice/", className = "webservice.impl.CalcularCustoResponse")
    @Action(input = "http://impl.webservice/EntregaEndpointWS/calcularCustoRequest", output = "http://impl.webservice/EntregaEndpointWS/calcularCustoResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://impl.webservice/EntregaEndpointWS/calcularCusto/Fault/Exception")
    })
    public Double calcularCusto(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Double arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        Double arg2)
        throws Exception_Exception
    ;

}
