
package webservice.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MalhaLogistica", targetNamespace = "http://impl.webservice/", wsdlLocation = "http://localhost:8080/smartlogic/ws/malhaLogistica?wsdl")
public class MalhaLogistica_Service
    extends Service
{

    private final static URL MALHALOGISTICA_WSDL_LOCATION;
    private final static WebServiceException MALHALOGISTICA_EXCEPTION;
    private final static QName MALHALOGISTICA_QNAME = new QName("http://impl.webservice/", "MalhaLogistica");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/smartlogic/ws/malhaLogistica?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MALHALOGISTICA_WSDL_LOCATION = url;
        MALHALOGISTICA_EXCEPTION = e;
    }

    public MalhaLogistica_Service() {
        super(__getWsdlLocation(), MALHALOGISTICA_QNAME);
    }

    public MalhaLogistica_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), MALHALOGISTICA_QNAME, features);
    }

    public MalhaLogistica_Service(URL wsdlLocation) {
        super(wsdlLocation, MALHALOGISTICA_QNAME);
    }

    public MalhaLogistica_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MALHALOGISTICA_QNAME, features);
    }

    public MalhaLogistica_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MalhaLogistica_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MalhaLogisticaEndpointWS
     */
    @WebEndpoint(name = "MalhaLogisticaEndpointWSPort")
    public MalhaLogisticaEndpointWS getMalhaLogisticaEndpointWSPort() {
        return super.getPort(new QName("http://impl.webservice/", "MalhaLogisticaEndpointWSPort"), MalhaLogisticaEndpointWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MalhaLogisticaEndpointWS
     */
    @WebEndpoint(name = "MalhaLogisticaEndpointWSPort")
    public MalhaLogisticaEndpointWS getMalhaLogisticaEndpointWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.webservice/", "MalhaLogisticaEndpointWSPort"), MalhaLogisticaEndpointWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MALHALOGISTICA_EXCEPTION!= null) {
            throw MALHALOGISTICA_EXCEPTION;
        }
        return MALHALOGISTICA_WSDL_LOCATION;
    }

}
